package org.example.gnucash.write;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.gnucash.numbers.FixedPointNumber;
import org.gnucash.write.GnucashWritableTransaction;
import org.gnucash.write.GnucashWritableTransactionSplit;
import org.gnucash.write.impl.GnucashWritableFileImpl;

public class GenTrx {
    // BEGIN Example data -- adapt to your needs
    private static String gcshInFileName     = "example_in.gnucash";
    private static String gcshOutFileName    = "example_out.gnucash";
    private static String fromAcctID         = "bbf77a599bd24a3dbfec3dd1d0bb9f5c"; // Root Account::Aktiva::Sichteinlagen::KK::Giro RaiBa
    private static String toAcctID           = "87b7dc076d684bb78044795a89d665c8"; // Root Account::Aktiva::Sichteinlagen::nicht-KK::Tagesgeld RaiBa
    private static FixedPointNumber amount   = new FixedPointNumber("1250/100");
    private static FixedPointNumber quantity = amount;
    private static LocalDate datePosted      = LocalDate.now();
    // END Example data

    // -----------------------------------------------------------------

    public static void main(String[] args) {
	try {
	    GenTrx tool = new GenTrx();
	    tool.kernel();
	} catch (Exception exc) {
	    System.err.println("Execution exception. Aborting.");
	    exc.printStackTrace();
	    System.exit(1);
	}
    }

    protected void kernel() throws Exception {
	GnucashWritableFileImpl gcshFile = new GnucashWritableFileImpl(new File(gcshInFileName));

	System.err.println("Account name (from): '" + gcshFile.getAccountByID(fromAcctID).getQualifiedName() + "'");
	System.err.println("Account name (to):   '" + gcshFile.getAccountByID(toAcctID).getQualifiedName() + "'");

	GnucashWritableTransaction trx = gcshFile.createWritableTransaction();
	trx.setDescription("Generated by GenTrx " + LocalDateTime.now().toString());

	GnucashWritableTransactionSplit split1 = trx.createWritingSplit(gcshFile.getAccountByID(fromAcctID));
	split1.setValue(new FixedPointNumber(amount.negate()));
	split1.setQuantity(new FixedPointNumber(quantity.negate()));

	GnucashWritableTransactionSplit split2 = trx.createWritingSplit(gcshFile.getAccountByID(toAcctID));
	split2.setValue(new FixedPointNumber(amount));
	split2.setQuantity(new FixedPointNumber(quantity));

	trx.setDatePosted(datePosted);
	trx.setDateEntered(LocalDateTime.now());

	System.out.println("Transaction to write: " + trx.toString());
	gcshFile.writeFile(new File(gcshOutFileName));
	System.out.println("OK");
    }
}
