package org.example.gnucash.write;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.gnucash.numbers.FixedPointNumber;
import org.gnucash.write.GnucashWritableTransaction;
import org.gnucash.write.GnucashWritableTransactionSplit;
import org.gnucash.write.impl.GnucashWritableFileImpl;

import org.example.CommandLineTool;
import org.example.CouldNotExecuteException;

public class GenTrx extends CommandLineTool
{
  // BEGIN Example data
  private static String           gcshInFileName  = "example_in.gnucash";
  private static String           gcshOutFileName = "example_out.gnucash";
  private static String           fromAcctID      = "xyz";
  private static String           toAcctID        = "xyz";
  private static FixedPointNumber amount          = new FixedPointNumber("1250/100");
  private static FixedPointNumber quantity        = amount;
  private static LocalDate        datePosted      = LocalDate.now();
  // END Example data
  
  // -----------------------------------------------------------------

  public static void main( String[] args )
  {
    try
    {
      GenTrx tool = new GenTrx ();
      tool.execute(args);
    }
    catch (CouldNotExecuteException exc) 
    {
      System.err.println("Execution exception. Aborting.");
      exc.printStackTrace();
      System.exit(1);
    }
  }

  @Override
  protected void kernel() throws Exception
  {
    GnucashWritableFileImpl gcshFile = new GnucashWritableFileImpl(new File(gcshInFileName));
    
    System.err.println("Account name (from): '" + gcshFile.getAccountByID(fromAcctID).getQualifiedName() + "'");
    System.err.println("Account name (to):   '" + gcshFile.getAccountByID(toAcctID).getQualifiedName() + "'");
    
    GnucashWritableTransaction trx = gcshFile.createWritableTransaction();
    trx.setDescription("Generated by GenTrx");

    GnucashWritableTransactionSplit split1 = trx.createWritingSplit(gcshFile.getAccountByID(fromAcctID));
    split1.setValue(new FixedPointNumber(amount.negate()));
    split1.setQuantity(new FixedPointNumber(quantity.negate()));
    
    GnucashWritableTransactionSplit split2 = trx.createWritingSplit(gcshFile.getAccountByID(toAcctID));
    split2.setValue(new FixedPointNumber(amount));
    split2.setQuantity(new FixedPointNumber(quantity));
    
    trx.setDatePosted(datePosted);
    trx.setDateEntered(LocalDateTime.now());
    
    gcshFile.writeFile(new File(gcshOutFileName));
    
    System.out.println(trx.getId());
  }
}
